-- Generated by tools/gen_fixtures.py from the specification's vectors.json. Do not edit.
module Fixtures where

import Data.Word (Word32, Word64)
import System.Random.Tandem (Quad (..))

-- | (o, h, o after T, h after T).
stepVectors :: [(Quad, Quad, Quad, Quad)]
stepVectors =
  [ (Quad 0x00000001 0x00000002 0x00000003 0x00000004, Quad 0x00000005 0x00000006 0x00000007 0x00000008, Quad 0x00000017 0x00150007 0x00000001 0x00050008, Quad 0x9e377ca9 0x0000e006 0x02000007 0x00001820)
  , (Quad 0x00000000 0x00000000 0x00000000 0x00000000, Quad 0x00000000 0x00000000 0x00000000 0x00000000, Quad 0x00000000 0x00000000 0x00000000 0x00000000, Quad 0x9e3779b9 0x00000000 0x00000000 0x00000000)
  ]

vectorKey :: Quad
vectorKey = Quad 0x00000001 0x00000002 0x00000003 0x00000004

-- | (counter, o, h) of F(key, counter, DOMAIN_STREAM, AUX_STREAM).
fVectors :: [(Word64, Quad, Quad)]
fVectors =
  [ (0, Quad 0x472bef12 0xc0977c66 0xd330ac3a 0xb11a020d, Quad 0xbfa0b6ba 0xecdbc48e 0xf1989116 0xc2374d96)
  , (1, Quad 0xb777c10c 0x2f6b5a5d 0x67a9ce03 0x7de06a50, Quad 0xd0c2dc4f 0xe1e50e0f 0x89efc72c 0x6e82b062)
  ]

-- | (index of the first 32-bit word, four words) under the vector key at K = 32.
streamWords :: [(Int, [Word32])]
streamWords =
  [ (0, [0x0a5bcb90, 0x6dfe98bc, 0x9612198a, 0xac115fd8])
  , (4, [0x33f598d7, 0xb5c280ca, 0x7a8e7b99, 0x8c362290])
  , (32, [0x9da7bac0, 0x4aca79eb, 0xbeb1f65a, 0xe2f0d5a1])
  ]

-- | (element, bits) of the Float64 and Float32 fills under the vector key.
vectorF64 :: [(Int, Word64)]
vectorF64 = [(0, 0x3fdb7fa62f0296f2), (16, 0x3fd2b29e7ae769ee)]

vectorF32 :: [(Int, Word32)]
vectorF32 = [(2, 0x3f161219)]

splitChild0, splitChild1, forkChild0, purpose7 :: Quad
splitChild0 = Quad 0xe256e9a1 0x5020f806 0x3bd3f7dc 0x5328763d
splitChild1 = Quad 0xa9ea3f0b 0x47f97af0 0xd1844c53 0x97e9cee2
forkChild0 = Quad 0x67fd37c5 0x9dc0b8c6 0x4e3bd55e 0xaf3f2216
purpose7 = Quad 0x8048398f 0x1678e814 0xd8823983 0xc4b1045c

seedValue :: Integer
seedValue = 42

seedKey :: Quad
seedKey = Quad 0x421d21eb 0x32d31777 0x62e7564b 0xdf2bdf82

seedF64 :: [(Int, Word64)]
seedF64 = [(0, 0x3fef74060c20bd01), (2, 0x3fde90e23dfe11f6), (16, 0x3fef03cc18171095)]

seedU32 :: [(Int, Word32)]
seedU32 = [(0, 0x05e80cec)]
