#!/usr/bin/env python3
"""Write the Float64 normal ziggurat tables of the specification as a Haskell module.

    python3 tools/gen_zig_tables.py ../tandem-spec/tables/normal_f64_zig1024.json \
      > src/System/Random/Tandem/ZigTables.hs

The input is the spec's table file, Appendix A "Normals". Its SHA-256 must match the value the
spec publishes, so a changed table file fails here instead of changing the normals.
"""

import hashlib
import json
import sys

SHA256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab"
LAYERS = 1024


def hexfloat(s):
    if float.fromhex(s).hex() != s:
        raise SystemExit(f"not a canonical hexadecimal float: {s}")
    return s


def rows(values, per_line):
    lines = [", ".join(values[i : i + per_line]) for i in range(0, len(values), per_line)]
    return "    [ " + "\n    , ".join(lines) + "\n    ]"


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    data = open(sys.argv[1], "rb").read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SHA256:
        raise SystemExit(f"{sys.argv[1]}: SHA-256 {digest}, expected {SHA256}")
    t = json.loads(data)
    if t["layers"] != LAYERS or len(t["W"]) != LAYERS or len(t["K"]) != LAYERS or len(t["Y"]) != LAYERS + 1:
        raise SystemExit("unexpected table sizes")
    w = [hexfloat(s) for s in t["W"]]
    k = [str(int(v)) for v in t["K"]]
    y = [hexfloat(s) for s in t["Y"]]
    print(f"""-- Generated by tools/gen_zig_tables.py from the spec's tables/normal_f64_zig1024.json
-- (SHA-256 {SHA256}). Do not edit.

-- | The Float64 normal ziggurat of Appendix A with {LAYERS} layers.
module System.Random.Tandem.ZigTables (zigR, zigW, zigK, zigY) where

import Data.Primitive.PrimArray (PrimArray, primArrayFromListN)
import Data.Word (Word64)

zigR :: Double
zigR = {hexfloat(t["R"])}

-- | @W[i]@ at @i@ for a clear sign bit and @-W[i]@ at @{LAYERS} + i@ for a set one, so the index is
-- the low 11 bits of a draw.
zigW :: PrimArray Double
zigW =
  primArrayFromListN
    {2 * LAYERS}
{rows(w + ["-" + s for s in w], 3)}
{{-# NOINLINE zigW #-}}

zigK :: PrimArray Word64
zigK =
  primArrayFromListN
    {LAYERS}
{rows(k, 6)}
{{-# NOINLINE zigK #-}}

zigY :: PrimArray Double
zigY =
  primArrayFromListN
    {LAYERS + 1}
{rows(y, 3)}
{{-# NOINLINE zigY #-}}""")


if __name__ == "__main__":
    main()
