#!/usr/bin/env python3
"""Haskell fixtures for tests/Main.hs from the specification's vectors.json. The bounded,
normal, exponential and choice fixtures are read from tests/conformance at run time.

    python3 tools/gen_fixtures.py ../tandem-spec/vectors.json > tests/Fixtures.hs

Floats are written as their bit patterns, so the tests compare bits.
"""
import json
import struct
import sys
from fractions import Fraction

vectors_path = sys.argv[1]


def f64_bits(s):
    return struct.unpack("<Q", struct.pack("<d", float(s)))[0]


def f32_bits(s):
    """The bits of the float nearest the decimal `s`, rounding the exact value once."""
    exact = Fraction(s.rstrip("fF"))
    guess = struct.unpack("<I", struct.pack("<f", float(exact)))[0]

    def value(bits):
        return Fraction(struct.unpack("<f", struct.pack("<I", bits))[0])

    near = [b for b in (guess - 1, guess, guess + 1) if 0 <= b < 0x7F800000 or b >= 0x80000000]
    return min(near, key=lambda b: (abs(value(b) - exact), b & 1))


def hs_list(xs, fmt):
    return "[" + ", ".join(fmt(x) for x in xs) + "]"


def hex32(x):
    return f"0x{x:08x}"


def hex64(x):
    return f"0x{x:016x}"


def quad(words):
    return "Quad " + " ".join(hex32(int(w, 16) if isinstance(w, str) else w) for w in words)


out = []
emit = out.append

emit("-- Generated by tools/gen_fixtures.py from the specification's vectors.json. Do not edit.")
emit("module Fixtures where")
emit("")
emit("import Data.Word (Word32, Word64)")
emit("import System.Random.Tandem (Quad (..))")
emit("")

# Specification vectors -------------------------------------------------------------------
v = json.load(open(vectors_path))
emit("-- | (o, h, o after T, h after T).")
emit("stepVectors :: [(Quad, Quad, Quad, Quad)]")
emit("stepVectors =")
emit("  [ " + "\n  , ".join(
    f"({quad(t['o'])}, {quad(t['h'])}, {quad(t['o_out'])}, {quad(t['h_out'])})" for t in v["T"]) + "\n  ]")
emit("")
emit("vectorKey :: Quad")
emit(f"vectorKey = {quad(v['key'])}")
emit("")
emit("-- | (counter, o, h) of F(key, counter, DOMAIN_STREAM, AUX_STREAM).")
emit("fVectors :: [(Word64, Quad, Quad)]")
emit("fVectors =")
emit("  [ " + "\n  , ".join(f"({f['counter']}, {quad(f['o'])}, {quad(f['h'])})" for f in v["F"]) + "\n  ]")
emit("")
emit("-- | (index of the first 32-bit word, four words) under the vector key at K = 32.")
emit("streamWords :: [(Int, [Word32])]")
emit("streamWords =")
emit("  [ " + "\n  , ".join(
    f"({s['first_word']}, {hs_list(s['words'], lambda w: hex32(int(w, 16)))})" for s in v["stream_words"]) + "\n  ]")
emit("")
d = v["draws_from_position_0"]
emit("-- | (element, bits) of the Float64 and Float32 fills under the vector key.")
emit("vectorF64 :: [(Int, Word64)]")
emit(f"vectorF64 = {hs_list(d['Float64'].items(), lambda kv: f'({kv[0]}, {hex64(f64_bits(str(kv[1])))})')}")
emit("")
emit("vectorF32 :: [(Int, Word32)]")
emit(f"vectorF32 = {hs_list(d['Float32'].items(), lambda kv: f'({kv[0]}, {hex32(f32_bits(str(kv[1])))})')}")
emit("")
k = v["derived_keys"]
emit("splitChild0, splitChild1, forkChild0, purpose7 :: Quad")
emit(f"splitChild0 = {quad(k['split_child_0'])}")
emit(f"splitChild1 = {quad(k['split_child_1'])}")
emit(f"forkChild0 = {quad(k['fork_child_0_at_block_0'])}")
emit(f"purpose7 = {quad(k['purpose_7'])}")
emit("")
s = v["seed_whitening"]
emit("seedValue :: Integer")
emit(f"seedValue = {s['seed']}")
emit("")
emit("seedKey :: Quad")
emit(f"seedKey = {quad(s['key'])}")
emit("")
emit("seedF64 :: [(Int, Word64)]")
emit(f"seedF64 = {hs_list(s['Float64'].items(), lambda kv: f'({kv[0]}, {hex64(f64_bits(str(kv[1])))})')}")
emit("")
emit("seedU32 :: [(Int, Word32)]")
emit(f"seedU32 = {hs_list(s['UInt32'].items(), lambda kv: f'({kv[0]}, {hex32(int(kv[1], 16))})')}")
emit("")

print("\n".join(out).rstrip())
