#!/usr/bin/env python3
"""Haskell fixtures for tests/Main.hs from the specification's vectors.json, tandem-c's
cross-check headers and tandem-cuda's fill headers.

    python3 tools/gen_fixtures.py ../tandem-spec/vectors.json ../tandem-c/tests ../tandem-cuda/tests \
      > tests/Fixtures.hs

Floats are written as their bit patterns, so the tests compare bits.
"""
import json
import re
import struct
import sys
from fractions import Fraction

vectors_path, c_tests, cuda_tests = sys.argv[1:4]


def header(name, tests=c_tests):
    with open(f"{tests}/{name}") as f:
        text = f.read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def initializer(text, name):
    """The brace initializer of array `name` as nested lists of number strings."""
    m = re.search(rf"\b{name}\s*\[[^\]]*\]\s*=\s*\{{", text)
    tokens = re.findall(r"[{},]|[^\s{},]+", text[m.end() - 1 :])
    stack, out = [[]], None
    for t in tokens:
        if t == "{":
            stack.append([])
        elif t == "}":
            done = stack.pop()
            stack[-1].append(done)
            if len(stack) == 1:
                out = stack[0][0]
                break
        elif t != ",":
            stack[-1].append(t)
    return out


def scalar(text, name):
    return re.search(rf"\b{name}\s*=\s*([0-9]+)", text).group(1)


def integer(s):
    return int(s.rstrip("uUlL"), 0)


def f64_bits(s):
    return struct.unpack("<Q", struct.pack("<d", float(s)))[0]


def f32_bits(s):
    """The bits of the float nearest the decimal `s`, rounding the exact value once."""
    exact = Fraction(s.rstrip("fF"))
    guess = struct.unpack("<I", struct.pack("<f", float(exact)))[0]

    def value(bits):
        return Fraction(struct.unpack("<f", struct.pack("<I", bits))[0])

    near = [b for b in (guess - 1, guess, guess + 1) if 0 <= b < 0x7F800000 or b >= 0x80000000]
    return min(near, key=lambda b: (abs(value(b) - exact), b & 1))


def hs_list(xs, fmt):
    return "[" + ", ".join(fmt(x) for x in xs) + "]"


def hex32(x):
    return f"0x{x:08x}"


def hex64(x):
    return f"0x{x:016x}"


def quad(words):
    return "Quad " + " ".join(hex32(int(w, 16) if isinstance(w, str) else w) for w in words)


out = []
emit = out.append

emit("-- Generated by tools/gen_fixtures.py from the specification's vectors.json, tandem-c's")
emit("-- cross-check headers and tandem-cuda's fill headers. Do not edit.")
emit("module Fixtures where")
emit("")
emit("import Data.Word (Word32, Word64)")
emit("import System.Random.Tandem (Quad (..))")
emit("")

# Specification vectors -------------------------------------------------------------------
v = json.load(open(vectors_path))
emit("-- | (o, h, o after T, h after T).")
emit("stepVectors :: [(Quad, Quad, Quad, Quad)]")
emit("stepVectors =")
emit("  [ " + "\n  , ".join(
    f"({quad(t['o'])}, {quad(t['h'])}, {quad(t['o_out'])}, {quad(t['h_out'])})" for t in v["T"]) + "\n  ]")
emit("")
emit("vectorKey :: Quad")
emit(f"vectorKey = {quad(v['key'])}")
emit("")
emit("-- | (counter, o, h) of F(key, counter, DOMAIN_STREAM, AUX_STREAM).")
emit("fVectors :: [(Word64, Quad, Quad)]")
emit("fVectors =")
emit("  [ " + "\n  , ".join(f"({f['counter']}, {quad(f['o'])}, {quad(f['h'])})" for f in v["F"]) + "\n  ]")
emit("")
emit("-- | (index of the first 32-bit word, four words) under the vector key at K = 32.")
emit("streamWords :: [(Int, [Word32])]")
emit("streamWords =")
emit("  [ " + "\n  , ".join(
    f"({s['first_word']}, {hs_list(s['words'], lambda w: hex32(int(w, 16)))})" for s in v["stream_words"]) + "\n  ]")
emit("")
d = v["draws_from_position_0"]
emit("-- | (element, bits) of the Float64 and Float32 fills under the vector key.")
emit("vectorF64 :: [(Int, Word64)]")
emit(f"vectorF64 = {hs_list(d['Float64'].items(), lambda kv: f'({kv[0]}, {hex64(f64_bits(str(kv[1])))})')}")
emit("")
emit("vectorF32 :: [(Int, Word32)]")
emit(f"vectorF32 = {hs_list(d['Float32'].items(), lambda kv: f'({kv[0]}, {hex32(f32_bits(str(kv[1])))})')}")
emit("")
k = v["derived_keys"]
emit("splitChild0, splitChild1, forkChild0, purpose7 :: Quad")
emit(f"splitChild0 = {quad(k['split_child_0'])}")
emit(f"splitChild1 = {quad(k['split_child_1'])}")
emit(f"forkChild0 = {quad(k['fork_child_0_at_block_0'])}")
emit(f"purpose7 = {quad(k['purpose_7'])}")
emit("")
s = v["seed_whitening"]
emit("seedValue :: Integer")
emit(f"seedValue = {s['seed']}")
emit("")
emit("seedKey :: Quad")
emit(f"seedKey = {quad(s['key'])}")
emit("")
emit("seedF64 :: [(Int, Word64)]")
emit(f"seedF64 = {hs_list(s['Float64'].items(), lambda kv: f'({kv[0]}, {hex64(f64_bits(str(kv[1])))})')}")
emit("")
emit("seedU32 :: [(Int, Word32)]")
emit(f"seedU32 = {hs_list(s['UInt32'].items(), lambda kv: f'({kv[0]}, {hex32(int(kv[1], 16))})')}")
emit("")

# Bounded draws ---------------------------------------------------------------------------
below = header("cross_below.h")
emit("-- | Scalar bounded draws from seed 42 at position 1: (range, draws, position after).")
for name, hs, ty in (("CROSS_U32", "below32", "Word32"), ("CROSS_U64", "below64", "Word64")):
    rows = initializer(below, name)
    emit(f"{hs} :: [({ty}, [{ty}], Word64)]")
    emit(f"{hs} =")
    emit("  [ " + "\n  , ".join(
        f"({integer(n)}, {hs_list(w, lambda x: str(integer(x)))}, {integer(e)})" for n, w, e in rows) + "\n  ]")
    emit("")

fill_below = header("cross_fill_below.h")
emit("-- | Bounded fills of 64 from seed 42: (start position, range, values, position after).")
for name, hs, ty in (("CROSS_FILL_U32", "crossFillBelow32", "Word32"), ("CROSS_FILL_U64", "crossFillBelow64", "Word64")):
    rows = initializer(fill_below, name)
    emit(f"{hs} :: [(Word64, {ty}, [{ty}], Word64)]")
    emit(f"{hs} =")
    emit("  [ " + "\n  , ".join(
        f"({integer(p)}, {integer(n)}, {hs_list(w, lambda x: str(integer(x)))}, {integer(e)})"
        for p, n, w, e in rows) + "\n  ]")
    emit("")

cuda_below = header("cross_fill_below.h", cuda_tests)
emit("-- | tandem-cuda's bounded fills of 64 from the key of seed 42.")
emit("cudaKey :: Quad")
emit(f"cudaKey = Quad {' '.join(hex32(integer(x)) for x in initializer(cuda_below, 'CROSS_FILL_KEY'))}")
emit("")
for name, hs, ty in (("CROSS_BELOW32", "cudaBelow32", "Word32"), ("CROSS_BELOW64", "cudaBelow64", "Word64")):
    rows = initializer(cuda_below, name)
    emit(f"-- | (range, rejected elements, values) from position 0.")
    emit(f"{hs} :: [({ty}, Int, [{ty}])]")
    emit(f"{hs} =")
    emit("  [ " + "\n  , ".join(
        f"({integer(n)}, {integer(r)}, {hs_list(w, lambda x: str(integer(x)))})" for n, r, w in rows) + "\n  ]")
    emit("")
for name, hs, ty in (("CROSS_BELOW32_AT", "cudaBelow32At", "Word32"), ("CROSS_BELOW64_AT", "cudaBelow64At", "Word64")):
    rows = initializer(cuda_below, name)
    emit(f"-- | (start position, range, rejected elements, values).")
    emit(f"{hs} :: [(Word64, {ty}, Int, [{ty}])]")
    emit(f"{hs} =")
    emit("  [ " + "\n  , ".join(
        f"({integer(p)}, {integer(n)}, {integer(r)}, {hs_list(w, lambda x: str(integer(x)))})"
        for p, n, r, w in rows) + "\n  ]")
    emit("")

# Normals and exponentials ----------------------------------------------------------------
normal = header("cross_normal.h")
emit("-- | Ziggurat normal fills of 64 from the key of seed 42: (start position, values, position after).")
emit("normals :: [(Word64, [Word64], Word64)]")
emit("normals =")
emit("  [ " + "\n  , ".join(
    f"({integer(p)}, {hs_list(w, lambda x: hex64(f64_bits(x)))}, {integer(e)})"
    for p, w, e in initializer(normal, "CROSS_NORMAL")) + "\n  ]")
emit("")
emit("-- | Flattened Box-Muller pairs from seed 42 at position 1, and the position after.")
emit("normalPairsFloat :: ([Word32], Word64)")
emit(f"normalPairsFloat = ({hs_list(initializer(normal, 'CROSS_NORMALF'), lambda x: hex32(f32_bits(x)))}, "
     f"{scalar(normal, 'CROSS_NORMALF_END_POS')})")
emit("")

cuda_normal = header("cross_fill_normal.h", cuda_tests)
emit("-- | tandem-cuda's normal fills from the key of seed 42: (start position, length, values).")
for name, hs, ty, bits in (("CROSS_NORMAL64", "cudaNormal64", "Word64", lambda x: hex64(f64_bits(x))),
                           ("CROSS_NORMAL32", "cudaNormal32", "Word32", lambda x: hex32(f32_bits(x)))):
    rows = initializer(cuda_normal, name)
    emit(f"{hs} :: [(Word64, Int, [{ty}])]")
    emit(f"{hs} =")
    emit("  [ " + "\n  , ".join(
        f"({integer(p)}, {integer(n)}, {hs_list(w[: integer(n)], bits)})" for p, n, w in rows) + "\n  ]")
    emit("")

exponential = header("cross_exponential.h")
emit("-- | Exponential fills of 64 from seed 42: (start position, values, position after).")
for name, hs, ty, bits in (("CROSS_EXPONENTIAL", "exponentials", "Word64", lambda x: hex64(f64_bits(x))),
                           ("CROSS_EXPONENTIALF", "exponentialsFloat", "Word32", lambda x: hex32(f32_bits(x)))):
    rows = initializer(exponential, name)
    emit(f"{hs} :: [(Word64, [{ty}], Word64)]")
    emit(f"{hs} =")
    emit("  [ " + "\n  , ".join(
        f"({integer(p)}, {hs_list(w, bits)}, {integer(e)})" for p, w, e in rows) + "\n  ]")
    emit("")

cuda_exponential = header("cross_fill_exponential.h", cuda_tests)
emit("-- | tandem-cuda's exponential fills from the key of seed 42: (start position, length, values).")
for name, hs, ty, bits in (("CROSS_EXP64", "cudaExponential64", "Word64", lambda x: hex64(f64_bits(x))),
                           ("CROSS_EXP32", "cudaExponential32", "Word32", lambda x: hex32(f32_bits(x)))):
    rows = initializer(cuda_exponential, name)
    emit(f"{hs} :: [(Word64, Int, [{ty}])]")
    emit(f"{hs} =")
    emit("  [ " + "\n  , ".join(
        f"({integer(p)}, {integer(n)}, {hs_list(w[: integer(n)], bits)})" for p, n, w in rows) + "\n  ]")
    emit("")

print("\n".join(out).rstrip())
